{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/he-gud-look/", "tag_product_ids": ["HE595WA94JJHINDFAS", "HE595WA24JIDINDFAS", "HE595WA92JJJINDFAS", "HE595WA08JITINDFAS", "HE595WA96JJFINDFAS", "HE595WA04VXFINDFAS", "HE595WA88JJNINDFAS", "HE595WA06JIVINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "The gud look"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/the-vanca/", "tag_product_ids": ["TH447WA50PKFINDFAS", "TH447WA28GDBINDFAS", "TH447WA69XWSINDFAS", "TH447WA68XWTINDFAS", "TH447WA66XWVINDFAS", "TH447WA67XWUINDFAS", "TH447WA70XWRINDFAS", "TH447WA95AEQINDFAS", "TH447WA74NQVINDFAS", "TH447WA75NQUINDFAS", "TH447WA48PKHINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "The Vanca"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/zinc-london/", "tag_product_ids": ["ZI218WA44SUHINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Zink London"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/the-tshirt-company/", "tag_product_ids": ["TH416WA36BHNINDFAS", "TH416WA35BHOINDFAS", "TH416WA80DNRINDFAS", "TH416WA32BHRINDFAS", "TH416WA33BHQINDFAS", "TH416WA34BHPINDFAS", "TH416WA37BHMINDFAS", "TH416WA82DNPINDFAS", "TH416WA87DNKINDFAS", "TH416WA92DNFINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Tshirt Company"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/uv-w/", "tag_product_ids": ["UV257WA40IRRINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "U V & W"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/vovoka/", "tag_product_ids": ["VO107WA60GGLINDFAS", "VO107WA64HFJINDFAS", "VO107WA68GRJINDFAS", "VO107WA72GRFINDFAS", "VO107WA67GGEINDFAS", "VO107WA69HFEINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Vovoka"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/trend18/", "tag_product_ids": ["TR400WA94RIBINDFAS", "TR400WA20GWLINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Trend18"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/Tommy_Hilfiger/", "tag_product_ids": ["TO348WA54ZNLINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Tommy Hilfiger"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/summer-jackets/vero-moda/", "tag_product_ids": ["VE693WA80NRNINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Summer Jackets", "Vero Moda"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/summer-jackets/the-vanca/", "tag_product_ids": ["TH447WA28GDBINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Summer Jackets", "The Vanca"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/summer-jackets/rinku-sobti/", "tag_product_ids": ["RI579WA38YSZINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Summer Jackets", "Rinku Sobti"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/tops-and-tunics/", "tag_product_ids": ["TO010WA12GVBINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Tops And Tunics"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/summer-jackets/svarikaa/", "tag_product_ids": ["SV148WA73KYKINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Summer Jackets", "Svarikaa"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/United-Colors-of-Benetton/", "tag_product_ids": ["UN573WA68OUXINDFAS", "UN573WA29LPYINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "United Colors of Benetton"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/suhi/", "tag_product_ids": ["SU289WA66ISRINDFAS", "SU289WA67ISQINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Suhi"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/the-vanca/", "tag_product_ids": ["TH447WA50PKFINDFAS", "TH447WA69XWSINDFAS", "TH447WA68XWTINDFAS", "TH447WA66XWVINDFAS", "TH447WA67XWUINDFAS", "TH447WA70XWRINDFAS", "TH447WA95AEQINDFAS", "TH447WA74NQVINDFAS", "TH447WA75NQUINDFAS", "TH447WA48PKHINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "The Vanca"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/he-gud-look/", "tag_product_ids": ["HE595WA04VXFINDFAS", "HE595WA06JIVINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "The gud look"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/w/", "tag_product_ids": ["XW574WA65WGCINDFAS", "XW574WA20XAD", "XW574WA21XAC", "XW574WA19XAE"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "W"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/tonga/", "tag_product_ids": ["TO382WA32XILINDFAS", "TO382WA18XIZINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Tonga"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/slumber-jill/", "tag_product_ids": ["SL200WA67VEYINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Slumber Jill"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/sportelle-usa-india/", "tag_product_ids": ["SP613WA22HXTINDFAS", "SP613WA23HXSINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Sportelle USA*INDIA"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/silverswan/", "tag_product_ids": ["SI653WA25HISINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Silverswan"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/senora/", "tag_product_ids": ["SE674WA36MPVINDFAS", "SE674WA34MPXINDFAS", "SE674WA35MPWINDFAS", "SE674WA33MPYINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Senora"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/sepia/", "tag_product_ids": ["SE182WA25UIOINDFAS", "SE182WA27UIMINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Sepia"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/sugar-her/", "tag_product_ids": ["SU903WA12VOTINDFAS", "SU903WA10VOVINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Sugar Her"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/river-island/", "tag_product_ids": ["RI264WA04UZBINDFAS", "RI264WA78DUJINDFAS", "RI264WA81DUGINDFAS", "RI264WA23GUIINDFAS", "RI264WA87GOEINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "River Island"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/sister-s-point/", "tag_product_ids": ["SI729WA62FORINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "SISTER'S POINT"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/people/", "tag_product_ids": ["PE138WA00ATJINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "People"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/raindrops/", "tag_product_ids": ["RA490WA66IUVINDFAS", "RA490WA60IVBINDFAS", "RA490WA22NZDINDFAS", "RA490WA34ADTINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Raindrops"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/rattrap/", "tag_product_ids": ["RA830WA12KNJINDFAS", "RA830WA34BRLINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Rattrap"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/ridress/", "tag_product_ids": ["RI314WA10UDLINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "RIDRESS"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/pab-jules/", "tag_product_ids": ["PA340WA64MBJINDFAS", "PA340WA65MBIINDFAS", "PA340WA66MBHINDFAS", "PA340WA52MBVINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Pab Jules"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/tokyo-talkies/", "tag_product_ids": ["TO817WA72DCLINDFAS", "TO817WA74DCJINDFAS", "TO817WA88FMPINDFAS", "TO817WA64IOHINDFAS", "TO817WA86FMRINDFAS", "TO817WA70DCNINDFAS", "TO817WA68DCPINDFAS", "TO817WA62IOJINDFAS", "TO817WA76DCHINDFAS", "TO817WA50FOBINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Tokyo Talkies"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/oviya/", "tag_product_ids": ["OV128WA99OPGINDFAS", "OV128WA98OPHINDFAS", "OV128WA93OPMINDFAS", "OV128WA96OPJINDFAS", "OV128WA97OPIINDFAS", "OV128WA95OPKINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Oviya"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/oxolloxo/", "tag_product_ids": ["OX344WA19CGEINDFAS", "OX344WA17CGGINDFAS", "OX344WA18CGFINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Oxolloxo"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/only/", "tag_product_ids": ["ON616WA46OBPINDFAS", "ON616WA28VUDINDFAS", "ON616WA50OBLINDFAS", "ON616WA03JLSINDFAS", "ON616WA89XTIINDFAS", "ON616WA77XTUINDFAS", "ON616WA98NZPINDFAS", "ON616WA10TVXINDFAS", "ON616WA82IZPINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Only"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/no-code/", "tag_product_ids": ["NO056WA96ZBJINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "NO CODE"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/new-look/", "tag_product_ids": ["NE499WA94OUVINDFAS", "NE499WA89HDIINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "New Look"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/peacot/", "tag_product_ids": ["PE332WA42FNHINDFAS", "PE332WA40FNJINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Peacot"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/nineteen/", "tag_product_ids": ["NI175WA32PDZINDFAS", "NI175WA35PDWINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "NINETEEN"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/mojo/", "tag_product_ids": ["MO581WA34JPTINDFAS", "MO581WA32JPVINDFAS", "MO581WA36JPRINDFAS", "MO581WA80EBJINDFAS", "MO581WA81EBIINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Mojo"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/mineral/", "tag_product_ids": ["MI472WA76RUTINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Mineral"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/miss-selfridge/", "tag_product_ids": ["MI479WA03WIAINDFAS", "MI479WA90URXINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Miss Selfridge"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/mayra/", "tag_product_ids": ["MA589WA45HOKINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Mayra"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/shibori-designs/", "tag_product_ids": ["SH566WA78VCBINDFAS", "SH566WA80VBZINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Shibori Designs"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/miss-bennett/", "tag_product_ids": ["MI162WA43QJSINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Miss Bennett"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/mango/", "tag_product_ids": ["MA092WA01JCWINDFAS", "MA092WA16QTVINDFAS", "MA092WA06IAVINDFAS", "MA092WA82JDPINDFAS", "MA092WA05IAWINDFAS", "MA092WA88GELINDFAS", "MA092WA08UCDINDFAS", "MA092WA02JCVINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Mango"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/mbe/", "tag_product_ids": ["MB786WA42YZLINDFAS", "MB786WA40YZNINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "MBE"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/Mustard/", "tag_product_ids": ["MU645WA73LESINDFAS", "MU645WA72LETINDFAS", "MU645WA77HWKINDFAS", "MU645WA71LEUINDFAS", "MU645WA59DCMINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Mustard"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/miaminx/", "tag_product_ids": ["MI863WA74OTDINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "MIAMINX"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/love-from-india/", "tag_product_ids": ["LO328WA06QBTINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Love From India"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/liebemode/", "tag_product_ids": ["LI964WA86ZFDINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Liebemode"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/kaxiaa/", "tag_product_ids": ["KA915WA34GKVINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Kaxiaa"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/my-sin/", "tag_product_ids": ["MY741WA50SLLINDFAS", "MY741WA48SLNINDFAS", "MY741WA46SLPINDFAS", "MY741WA98SNLINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "MySin"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/identiti/", "tag_product_ids": ["ID280WA19RSEINDFAS", "ID280WA10AJXINDFAS", "ID280WA08AJZINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Identiti"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/harpa/", "tag_product_ids": ["HA585WA42UPPINDFAS", "HA585WA70ASFINDFAS", "HA585WA50UPHINDFAS", "HA585WA14AUJINDFAS", "HA585WA72ASDINDFAS", "HA585WA12AULINDFAS", "HA585WA44UPNINDFAS", "HA585WA18UMRINDFAS", "HA585WA48UPJINDFAS", "HA585WA94ZHXINDFAS", "HA585WA27ZGQINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Harpa"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/arista/", "tag_product_ids": ["AR417WA64ZBBINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "La Arista"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/Global_Desi/", "tag_product_ids": ["GL063WA90FDXINDFAS", "GL063WA67HTOINDFAS", "GL063WA06FDHINDFAS", "GL063WA88AEPINDFAS", "GL063WA04FDJINDFAS", "GL063WA47HUIINDFAS", "GL063WA58FZXINDFAS", "GL063WA00KFBINDFAS", "GL063WA28KDZINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Global Desi"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/glam-luxe/", "tag_product_ids": ["GL298WA42DTPINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Glam & Luxe"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/globus/", "tag_product_ids": ["GL409WA36YRRINDFAS", "GL409WA60YJBINDFAS", "GL409WA26YCRINDFAS", "GL409WA34QUZINDFAS", "GL409WA28ARNINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Globus"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/Fusion-Beats/", "tag_product_ids": ["FU277WA78NAZINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Fusion Beats"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/femenino/", "tag_product_ids": ["FE857WA06VXTINDFAS", "FE857WA04VXVINDFAS", "FE857WA02VXXINDFAS", "FE857WA40VWLINDFAS", "FE857WA48VWDINDFAS", "FE857WA00VXZINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Femenino"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/martini/", "tag_product_ids": ["MA548WA70TRPINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Martini"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/gipsy/", "tag_product_ids": ["GI372WA42IERINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Gipsy"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/elle/", "tag_product_ids": ["EL144WA33RUKINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Elle"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/Femella/", "tag_product_ids": ["FE248WA08ESPINDFAS", "FE248WA16ESHINDFAS", "FE248WA08KRNINDFAS", "FE248WA90RIZINDFAS", "FE248WA73PCWINDFAS", "FE248WA91RIYINDFAS", "FE248WA28TPBINDFAS", "FE248WA38NSZINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Femella"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/dorothy-perkins/", "tag_product_ids": ["DO102WA44PNBINDFAS", "DO102WA22PGFINDFAS", "DO102WA34JEJINDFAS", "DO102WA33JEKINDFAS", "DO102WA36JEHINDFAS", "DO102WA36RBBINDFAS", "DO102WA57IFMINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Dorothy Perkins"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/color_cocktail/", "tag_product_ids": ["CO574WA27XEMINDFAS", "CO574WA94PXPINDFAS", "CO574WA19NYEINDFAS", "CO574WA98PXLINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Color Cocktail"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/code/", "tag_product_ids": ["CO788WA60OOLINDFAS", "CO788WA66OOFINDFAS", "CO788WA76ONVINDFAS", "CO788WA77CKSINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Code"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/bronz/", "tag_product_ids": ["BR737WA13TTYINDFAS", "BR737WA15TTWINDFAS", "BR737WA14TTXINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Bronz"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/calgari/", "tag_product_ids": ["CA605WA28OSTINDFAS", "CA605WA24OSXINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Calgari"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/meee/", "tag_product_ids": ["ME549WA51QFWINDFAS", "ME549WA48GAHINDFAS", "ME549WA85UHAINDFAS", "ME549WA02BGNINDFAS", "ME549WA56QFRINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "MEEE"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/b-kind/", "tag_product_ids": ["BK505WA54LHXINDFAS", "BK505WA56LHVINDFAS", "BK505WA58LHTINDFAS", "BK505WA24ACHINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "B.Kind"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/avirate/", "tag_product_ids": ["AV510WA37JCSINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Avirate"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/arrow-woman/", "tag_product_ids": ["AR262WA53DMCINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Arrow Woman"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/athena/", "tag_product_ids": ["AT732WA40CVJINDFAS", "AT732WA39CVKINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Athena"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/belle-fille/", "tag_product_ids": ["BE797WA98QVLINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Belle Fille"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/aks/", "tag_product_ids": ["AK304WA68LBZINDFAS", "AK304WA66LCBINDFAS", "AK304WA10GZDINDFAS", "AK304WA42BPLINDFAS", "AK304WA52KBRINDFAS", "AK304WA54KBPINDFAS", "AK304WA60LCHINDFAS", "AK304WA50KBTINDFAS", "AK304WA58KBLINDFAS", "AK304WA64LCDINDFAS", "AK304WA62LCFINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Aks"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/109F/", "tag_product_ids": ["10278WA46QMRINDFAS", "10278WA42QMVINDFAS", "10029WA56QATINDFAS", "10278WA48QMPINDFAS", "10278WA38QMZINDFAS", "10278WA50QMNINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "109\u00b0F"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/And/", "tag_product_ids": ["AN012WA89IGCINDFAS", "AN012WA64CDBINDFAS", "AN012WA03EWEINDFAS", "AN012WA00CBRINDFAS", "AN012WA93YGKINDFAS", "AN012WA56PTZINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "AND"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/Lara-Karen/", "tag_product_ids": ["LA037WA46SUZINDFAS", "LA037WA49CXMINDFAS", "LA037WA02RVTINDFAS", "LA037WA48CXNINDFAS", "LA037WA01RVUINDFAS", "LA037WA57BNUINDFAS", "LA037WA60LLBINDFAS", "LA037WA61LLAINDFAS", "LA037WA62LKZINDFAS", "LA037WA47SUYINDFAS", "LA037WA56BNVINDFAS", "LA037WA32SCHINDFAS", "LA037WA31SCIINDFAS", "LA037WA30SCJINDFAS", "LA037WA55BNWINDFAS", "LA037WA58BNTINDFAS", "LA037WA77UCSINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Lara Karen"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/vero-moda/", "tag_product_ids": ["VE693WA80YFRINDFAS", "VE693WA15QTGINDFAS", "VE693WA57SFMINDFAS", "VE693WA64XSLINDFAS", "VE693WA92VSXINDFAS", "VE693WA00JTVINDFAS", "VE693WA19QTCINDFAS", "VE693WA25DTYINDFAS", "VE693WA00NFZINDFAS", "VE693WA36BQLINDFAS", "VE693WA90GCBINDFAS", "VE693WA55ILGINDFAS", "VE693WA62NDPINDFAS", "VE693WA04FXRINDFAS", "VE693WA01SXYINDFAS", "VE693WA46CGBINDFAS", "VE693WA02FXTINDFAS", "VE693WA83XRSINDFAS", "VE693WA08FXNINDFAS", "VE693WA92JBZINDFAS", "VE693WA58KDDINDFAS", "VE693WA72GUPINDFAS", "VE693WA94JBXINDFAS", "VE693WA98BRXINDFAS", "VE693WA20GUDINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Vero Moda"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/summer-jackets/pluss/", "tag_product_ids": ["PL299WA71TKYINDFAS", "PL299WA72TKXINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Summer Jackets", "Pluss"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/ten-on-ten/", "tag_product_ids": ["TE478WA24IWTINDFAS", "TE478WA22IWVINDFAS", "TE478WA16IXBINDFAS", "TE478WA26IWRINDFAS", "TE478WA20IWXINDFAS", "TE478WA34IWJINDFAS", "TE478WA30IWNINDFAS", "TE478WA14IXDINDFAS", "TE478WA23GMQINDFAS", "TE478WA02OQRINDFAS", "TE478WA94OQZINDFAS", "TE478WA08OQLINDFAS", "TE478WA72ORVINDFAS", "TE478WA04OQPINDFAS", "TE478WA52OSPINDFAS", "TE478WA28IWPINDFAS", "TE478WA36IWHINDFAS", "TE478WA66OSBINDFAS", "TE478WA10OQJINDFAS", "TE478WA64OSDINDFAS", "TE478WA50OSRINDFAS", "TE478WA32IWLINDFAS", "TE478WA70ORXINDFAS", "TE478WA38IWFINDFAS", "TE478WA80ORNINDFAS", "TE478WA08EXZINDFAS", "TE478WA16OQDINDFAS", "TE478WA12OQHINDFAS", "TE478WA18IWZINDFAS", "TE478WA21GMSINDFAS", "TE478WA84ORJINDFAS", "TE478WA54OSNINDFAS", "TE478WA96OQXINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Ten On Ten"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/softwear/", "tag_product_ids": ["SO308WA43SVGINDFAS", "SO308WA45SVEINDFAS", "SO308WA49SVAINDFAS", "SO308WA57SUSINDFAS", "SO308WA53SUWINDFAS", "SO308WA51SUYINDFAS", "SO308WA46SVDINDFAS", "SO308WA90NXPINDFAS", "SO308WA50SUZINDFAS", "SO308WA44SVFINDFAS", "SO308WA47SVCINDFAS", "SO308WA40SVJINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Softwear"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/French_Connection/", "tag_product_ids": ["FR332WA39WJWINDFAS", "FR332WA97WLMINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "French Connection"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/S.Oliver/", "tag_product_ids": ["SO557WA50QANINDFAS", "SO557WA90QWBINDFAS", "SO557WA34FVTINDFAS", "SO557WA54QAJINDFAS", "SO557WA84QKTINDFAS", "SO557WA56QAHINDFAS", "SO557WA78QKZINDFAS", "SO557WA04QJZINDFAS", "SO557WA46QARINDFAS", "SO557WA48QAPINDFAS", "SO557WA08QJVINDFAS", "SO557WA02QKBINDFAS", "SO557WA86PZDINDFAS", "SO557WA12QJRINDFAS", "SO557WA64QLNINDFAS", "SO557WA06QJXINDFAS", "SO557WA46QMFINDFAS", "SO557WA80QKXINDFAS", "SO557WA04QCHINDFAS", "SO557WA54QLXINDFAS", "SO557WA52QALINDFAS", "SO557WA82QKVINDFAS", "SO557WA48QMDINDFAS", "SO557WA14QBXINDFAS", "SO557WA60QLRINDFAS", "SO557WA50QMBINDFAS", "SO557WA46QIJINDFAS", "SO557WA20QUXINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "s.Oliver"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/summer-jackets/ladybug/", "tag_product_ids": ["LA871WA40COLINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Summer Jackets", "Ladybug"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/summer-jackets/oxolloxo/", "tag_product_ids": ["OX344WA90VSRINDFAS", "OX344WA88VSTINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Summer Jackets", "Oxolloxo"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/summer-jackets/anita-dogre/", "tag_product_ids": ["AN136WA80SUDINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Summer Jackets", "Anita Dongre"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/summer-jackets/Global_Desi/", "tag_product_ids": ["GL063WA98QIZINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Summer Jackets", "Global Desi"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/summer-jackets/Adidas/", "tag_product_ids": ["AD004WA22MIFINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Summer Jackets", "Adidas"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/summer-jackets/femenino/", "tag_product_ids": ["FE857WA18WBDINDFAS", "FE857WA78VYVINDFAS", "FE857WA20WBBINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Summer Jackets", "Femenino"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/summer-jackets/sampada/", "tag_product_ids": ["SA825WA98SBDINDFAS", "SA825WA96SBFINDFAS", "SA825WA04SAXINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Summer Jackets", "Sampada"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/summer-jackets/tarama/", "tag_product_ids": ["TA820WA68TVJINDFAS", "TA820WA70TVHINDFAS", "TA820WA64TVNINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Summer Jackets", "Tarama"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/espresso/", "tag_product_ids": ["ES418WA52LBRINDFAS", "ES418WA53LBQINDFAS", "ES418WA57LBMINDFAS", "ES418WA36NLZINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Espresso"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/summer-jackets/he-gud-look/", "tag_product_ids": ["HE595WA94JJHINDFAS", "HE595WA24JIDINDFAS", "HE595WA92JJJINDFAS", "HE595WA08JITINDFAS", "HE595WA96JJFINDFAS", "HE595WA88JJNINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Summer Jackets", "The gud look"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/raindrops/", "tag_product_ids": ["RA490WA66IUVINDFAS", "RA490WA60IVBINDFAS", "RA490WA34AMVINDFAS", "RA490WA32AMXINDFAS", "RA490WA22NZDINDFAS", "RA490WA36AMTINDFAS", "RA490WA34ADTINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Raindrops"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/oxolloxo/", "tag_product_ids": ["OX344WA90VSRINDFAS", "OX344WA19CGEINDFAS", "OX344WA17CGGINDFAS", "OX344WA18CGFINDFAS", "OX344WA88VSTINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Oxolloxo"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/ladybug/", "tag_product_ids": ["LA871WA06CPTINDFAS", "LA871WA40COLINDFAS", "LA871WA08CPRINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Ladybug"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/alia-bhatt-for-jabong/", "tag_product_ids": ["AL380WA75ESMINDFAS", "AL380WA51DVGINDFAS", "AL380WA71ESQINDFAS", "AL380WA73ESOINDFAS", "AL380WA61ETAINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Alia Bhatt For Jabong"]}
{"product_item_num": "http://www.jabong.com", "tag_product_ids": [], "tag": []}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/Global_Desi/", "tag_product_ids": ["GL063WA90FDXINDFAS", "GL063WA67HTOINDFAS", "GL063WA98QIZINDFAS", "GL063WA06FDHINDFAS", "GL063WA88AEPINDFAS", "GL063WA04FDJINDFAS", "GL063WA47HUIINDFAS", "GL063WA58FZXINDFAS", "GL063WA00KFBINDFAS", "GL063WA28KDZINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Global Desi"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/femenino/", "tag_product_ids": ["FE857WA06VXTINDFAS", "FE857WA04VXVINDFAS", "FE857WA02VXXINDFAS", "FE857WA40VWLINDFAS", "FE857WA18WBDINDFAS", "FE857WA78VYVINDFAS", "FE857WA20WBBINDFAS", "FE857WA48VWDINDFAS", "FE857WA00VXZINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Femenino"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/summer-jackets/raindrops/", "tag_product_ids": ["RA490WA34AMVINDFAS", "RA490WA32AMXINDFAS", "RA490WA36AMTINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Summer Jackets", "Raindrops"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/vero-moda/", "tag_product_ids": ["VE693WA80YFRINDFAS", "VE693WA15QTGINDFAS", "VE693WA57SFMINDFAS", "VE693WA64XSLINDFAS", "VE693WA92VSXINDFAS", "VE693WA00JTVINDFAS", "VE693WA19QTCINDFAS", "VE693WA25DTYINDFAS", "VE693WA00NFZINDFAS", "VE693WA36BQLINDFAS", "VE693WA90GCBINDFAS", "VE693WA55ILGINDFAS", "VE693WA62NDPINDFAS", "VE693WA04FXRINDFAS", "VE693WA01SXYINDFAS", "VE693WA46CGBINDFAS", "VE693WA80NRNINDFAS", "VE693WA02FXTINDFAS", "VE693WA83XRSINDFAS", "VE693WA08FXNINDFAS", "VE693WA92JBZINDFAS", "VE693WA58KDDINDFAS", "VE693WA72GUPINDFAS", "VE693WA94JBXINDFAS", "VE693WA98BRXINDFAS", "VE693WA20GUDINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Vero Moda"]}
{"product_item_num": "http://www.jabong.com/women/clothing/summer-jackets-shrugs/shrugs/ladybug/", "tag_product_ids": ["LA871WA06CPTINDFAS", "LA871WA08CPRINDFAS"], "tag": ["Women", "Clothing", "Summer Jackets & Shrugs", "Shrugs", "Ladybug"]}
